name: devfest_florida_app
description: DevFest Florida conference app for speakers, schedules and more.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^0.4.0
  shared_preferences: ^0.2.4+1
  font_awesome_flutter: 4.7.2
  image_picker: ^0.0.2
  firebase_analytics: ^0.0.2
  firebase_auth: ^0.0.2
  firebase_database: ^0.0.14
  uuid: ^0.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/devfest-logo.png

  fonts:
    - family: FontAwesome
      fonts:
        - asset: packages/font_awesome_flutter/fonts/fontawesome.woff
    - family: FloridaProject-PhaseOne
      fonts:
        - asset: assets/fonts/FloridaProjectPhaseOne.ttf
